### ISSUE TITLE
Add explanation for colour scale

### ISSUE THREAD

**Issue by jrgwhiteford** [RobJN/regional-fes#30]
Adding a clear explanation of how to adjust the colour scale similar to the explanation on UKPN's version of their tool

**Comment by slowe** [comment]
@jrgwhiteford These are my suggested changes:

1. Change the colour scale toggle to read:
    >  Adjust colour scale to current year? Yes / No
    > Selecting __Yes__ will improve contrast between areas within your chosen year. Selecting __No__ will use the same colour scale across all the years so is best for comparing over time.
2. Move the toggle and text below the colour scale (under the map) so that it is visually connected to the colour scale e.g.
![Screenshot 2022-05-10 at 11-49-05 Regional Breakdown of FES 2021 Data (Electricity)](https://user-images.githubusercontent.com/299787/167612122-cb97e853-c7af-42aa-a724-13cda7eec9cb.png)

**Comment by slowe** [comment]
@jrgwhiteford These cahnges have now been merged by @RobJN so I think this issue can be closed.

**Comment by jrgwhiteford** [comment]
Issue closed
